# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 07:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0029_auto_20181219_0950'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='job',
        #    name='download_compress_status',
        #    field=models.CharField(default='Download starting', max_length=32),
        #),
        migrations.AlterField(
            model_name='job',
            name='device_type',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='vts_squad.LavaDeviceType'),
        ),
        migrations.AlterField(
            model_name='job',
            name='vts_version',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='vts_squad.VtsVersion'),
        ),
        migrations.AlterField(
            model_name='lavadevicetype',
            name='squad_api',
            field=models.ForeignKey( on_delete=django.db.models.deletion.CASCADE, to='vts_squad.SquadAPI'),
        ),
    ]
