# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 07:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0033_auto_20181221_0751'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='job',
        #    name='download_compress_status',
        #    field=models.CharField(default='Download starting', max_length=32),
        #),
    ]
