# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 09:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0036_auto_20181221_0907'),
    ]

    operations = [
        #migrations.AddField(
        #    model_name='job',
        #    name='download_compress_status',
        #    field=models.CharField(default='Download starting', max_length=32),
        #),
        migrations.AlterField(
            model_name='job',
            name='jenkins_build_type',
            field=models.CharField(default='', max_length=16),
        ),
        migrations.AlterField(
            model_name='job',
            name='jenkins_lavatest',
            field=models.CharField(default='', max_length=16),
        ),
    ]
