# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 09:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0038_auto_20181221_0911'),
    ]

    operations = [
    ]
