# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2018-12-21 11:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vts_squad', '0041_auto_20181221_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='lava_job',
            field=models.CharField(default='', max_length=64),
        ),
        migrations.AlterField(
            model_name='job',
            name='lava_job_status',
            field=models.CharField(default='Submitted', max_length=32),
        ),
    ]
